language: c++
sudo: false

script:
  - cmake -DCMAKE_BUILD_TYPE=Release
  - make -j
  - bin/unitTests
  
before_script:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  
matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER='g++-4.9'
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake