language: c++
sudo: false
os:
  - linux
  - osx
compiler: 
  - clang
  - gcc
script:
  - cmake -DCMAKE_BUILD_TYPE=Release
  - make -j
  - bin/unitTests
addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake-data
      - cmake
      - g++-4.9
